First push of the developer documentation
automl/Auto-PyTorch pull request #127
Opened 2021-03-08 19:33 UTC by franchuterivera

First Push for the developer documentation.

2021-03-18 11:57 UTC, franchuterivera commented
Also, add documentation for the run identifiers

2021-03-23 18:20 UTC, ravinkohli commented on docs/dev.rst
> +translated to a pipeline configuration, fitted and saved to disc using the function evaluator `ExecuteTaFuncWithQueue`. The later is basically a worker that that
It should be the latter is basically

2021-04-07 11:26 UTC, ravinkohli commented on docs/dev.rst
> +This documentation summarizes how the AutoPyTorch code works, and it is meant to guide developers
and is meant as a guide for the developers to help contribute to it. Maybe?

2021-04-07 11:27 UTC, ravinkohli commented on docs/dev.rst
> +Therefore, there are two main parts of the code: `AutoMLSMBO`, which is our interface to the SMAC package, and
AutoMLSMBO, which acts as an interface to SMAC

2021-04-07 11:37 UTC, ravinkohli commented on docs/dev.rst
> +In other words, each of the individual models fitted by SMAC are (and comply) with Scikit-Learn pipeline and framework. For example, when a pipeline is fitted,
A pipeline can consist of various preprocessing steps including- imputation, encoding, scaling, and feature preprocessing for tabular data followed by the setup of the training algorithm which includes building a network embedding for categorical features, a network backbone that is responsible for feature extraction, a network head that is responsible for decision making and choosing an appropriate Learning Rate scheduler, optimisation algorithm, and initialisation of the network parameters. 

The preprocessing steps are aggregated into a Sklearn ColumnTransformer to maintain the order of the columns and the column transformer is wrapped into a TabularColumnTransformer class which complies with a torchvision transform. Based on the size of the dataset, we apply this transformer to the whole of the dataset in the EarlyPreprocessing node if the dataset is small enough or it is added as a transform to the data loader object that allows transforming the dataset batchwise.

2021-04-07 11:43 UTC, ravinkohli commented on docs/dev.rst
> +translated to a pipeline configuration, fitted and saved to disc using the function evaluator `ExecuteTaFuncWithQueue`. The latter is basically a worker that that
These configurations are then translated to AutoPyTorch pipelines, fitted, and finally saved to disc

2021-04-07 11:44 UTC, ravinkohli commented on docs/dev.rst
> +translated to a pipeline configuration, fitted and saved to disc using the function evaluator `ExecuteTaFuncWithQueue`. The latter is basically a worker that that
These configurations are then translated to AutoPyTorch pipelines, fitted, and finally saved to disc

2021-04-07 11:45 UTC, ravinkohli commented on docs/dev.rst
> +resources using `Pynisher <https://github.com/automl/pynisher>`_, and it usually does so by creating a new process.
memory and time constraints, maybe?

2021-04-07 11:47 UTC, ravinkohli commented on docs/dev.rst
> +The Scikit-learn pipeline inherits from the `BaseEstimator <https://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html>`_, which implies that we have to honor the `Scikit-Learn
Particularly, the arguments that the class constructor of any estimator must be defined as attributes of the class. (see blah blah)

2021-04-07 11:49 UTC, ravinkohli commented on docs/dev.rst
> +Regarding multiprocessing, AutoPyTorch and SMAC work with `Dask.distributed <https://distributed.dask.org/en/latest/>`_. We only submits jobs to Dask up to the number of
To speed up the search, AutoPyTorch and SMAC use Dask.distributed which provides an excellent(or good) infrastructure to effectively multiprocess the computations involved.

2021-04-07 11:49 UTC, ravinkohli commented on docs/dev.rst
> +At the end of a SMAC runs, the results will be available in the `temporary_directory` provided to the API, in particular inside of the `<temporary_directory>/smac3-output/run_<SEED>/` directory. One
run*

2021-04-07 11:50 UTC, ravinkohli commented on docs/dev.rst
> +In this later directory we store the fitted model (during cross-validation we store a single Voting Classifier/Regressor, which is the soft voting outcome of k-Fold cross-validation), the Out-Of-Fold
In this 'runs' directory,

2021-04-07 11:52 UTC, ravinkohli commented on docs/dev.rst
> +In other words, each of the individual models fitted by SMAC are (and comply) with Scikit-Learn pipeline and framework. For example, when a pipeline is fitted,
This can also be moved to the end (AutoML part) where you talk about the pipeline

2021-04-07 11:53 UTC, ravinkohli requested changes
Hey, this documentation overall looks good and provides important details of the working of AutoPyTorch. I have made some comments that may improve the information we give to the developers and also minor grammar updates. All these are optional, please choose what you also see as appropriate

2021-04-07 15:29 UTC, ravinkohli commented on docs/dev.rst
> +This documentation summarizes how the AutoPyTorch code works, and is meant as a guide for the developers to help contribute to it. .
there is an extra .

2021-04-07 15:29 UTC, ravinkohli approved these changes
There is a minor typo but otherwise it looks great.

2021-04-15 12:15 UTC, merged