[ADD] Extra visualization example
automl/Auto-PyTorch pull request #189
Opened 2021-04-28 20:49 UTC by franchuterivera

In preparation to move the refactor_development branch to be development, we were missing:

* User details in the documentation
* Examples with visualization

This PR aims to fix this.

2021-04-28 21:00 UTC, ravinkohli commented on docs/manual.rst
> +However, you are welcome to contribute to this documentation but starting a Pull-Request.
by making a Pull Request?

2021-04-28 21:02 UTC, ravinkohli commented on docs/manual.rst
> +Additionally, one can control the allocated time to search for a model, via the argument `total_walltime_limit` to the `search()` method. The later controls how much time SMAC can search for new conf
the latter* controls

2021-04-28 21:03 UTC, ravinkohli commented on docs/manual.rst
> +Additionally, one can control the allocated time to search for a model, via the argument `total_walltime_limit` to the `search()` method. The later controls how much time SMAC can search for new conf
Actually I dont think you need to put latter here. it seems like you are talking about the search method

2021-04-28 21:32 UTC, ravinkohli commented on docs/manual.rst
> +However, you are welcome to contribute to this documentation but starting a Pull-Request.
```suggestion
However, you are welcome to contribute to this documentation by making a Pull-Request.
```

2021-04-28 21:34 UTC, ravinkohli commented on docs/manual.rst
> +Additionally, one can control the allocated time to search for a model, via the argument `total_walltime_limit` to the `search()` method. The later controls how much time SMAC can search for new conf
```suggestion
Additionally, one can control the allocated time to search for a model, via the argument `total_walltime_limit` to the `search()` method. This argument controls how much time SMAC can search for new configurations to solve the problem at hand. The more time is allocated, the better the final estimator will be.
```

2021-04-28 21:55 UTC, ravinkohli reviewed
Thank you for this PR. It shows vital features of the API and the extensive compatibility with sklearn API. I have made minor suggestions in the documentation but other than that, it can be merged

2021-04-29 09:10 UTC, franchuterivera commented
Thanks a lot for the suggestions, I have committed them!

2021-04-29 09:12 UTC, ravinkohli approved these changes

2021-04-29 09:15 UTC, ravinkohli commented
Actually could you also change the version [here](https://github.com/franchuterivera/Auto-PyTorch/blob/fb370c739ba0d2b593bedabc6b7ef3f7cf097d19/autoPyTorch/__version__.py#L4)

2021-05-01 14:14 UTC, ArlindKadra commented
Really nice example :)

2021-05-01 17:02 UTC, ravinkohli commented on examples/tabular/40_advanced/example_visualization.py
> +        title='Auto-sklearn accuracy over time',
```suggestion
        title='Auto-PyTorch accuracy over time',
```

2021-05-05 08:12 UTC, nabenabe0928 requested changes

2021-05-05 08:12 UTC, nabenabe0928 commented on docs/manual.rst
> +* ``ensemble_nbest`` allows the user to directly specify the number of models considered for the ensemble.  This hyperparameter can be an integer *n*, such that only the best *n* models are used in t
> This hyperparameter can be an integer n, such that only the best *n* models are used in the final ensemble

When an integer is provided for this hyperparameter, the final ensemble chooses each predictor from only the best n models

> If a float between 0.0 and 1.0 is provided, ``ensemble_nbest`` would be interpreted as a fraction suggesting the percentage of models to use in the ensemble building process

If a float between 0.0 and 1.0 is provided, ``ensemble_nbest`` will be interpreted as a fraction suggesting the percentage of models to use in the ensemble building process.
For example, when we train 10 models before the ensemble building process and the hyperparameter is 0.7, we build an ensemble by taking some models from only **best (?)** 7 models among 10 models.

2021-05-05 08:12 UTC, nabenabe0928 commented on docs/manual.rst
> +* ``max_models_on_disc`` defines the maximum number of models that are kept on the disc, as a mechanism to control the amount of disc space consumed by *auto-sklearn*. Throughout the automl process,
> the maximum number of models that are kept on the disc

the maximum number of models that can stay on the disc

> the amount of disc space consumed by *auto-sklearn*

auto-pytorch?

> their predictions (and other metadata) is stored on disc. 

are stored

2021-05-05 08:12 UTC, nabenabe0928 commented on examples/tabular/40_advanced/example_visualization.py
> +"""
Haven't checked yet

2021-05-06 01:15 UTC, nabenabe0928 commented on examples/tabular/40_advanced/example_visualization.py
> +os.environ['MKL_NUM_THREADS'] = '1'
What about those environment variables?
We need explanations for them.

2021-05-07 03:57 UTC, nabenabe0928 approved these changes

2021-05-07 03:57 UTC, merged