[feat] Support statistics print by adding results manager object
automl/Auto-PyTorch pull request #334
Opened 2021-11-19 13:28 UTC by nabenabe0928

This PR addresses the [ISSUE#326](https://github.com/automl/Auto-PyTorch/issues/326) and took over the ownership from the [PR#332](https://github.com/automl/Auto-PyTorch/pull/332) authored by @ravinkohli .

2021-11-19 13:30 UTC, nabenabe0928 commented
Toy example is the following:
```
import warnings

import numpy as np
import pandas as pd

from sklearn import model_selection

from autoPyTorch.api.tabular_classification import TabularClassificationTask


warnings.simplefilter(action='ignore', category=UserWarning)
warnings.simplefilter(action='ignore', category=FutureWarning)


n_samples, dim = 50, 2
X = np.random.random((n_samples, dim)) * 2 - 1
y = ((X ** 2).sum(axis=-1) < 2 / np.pi).astype(np.int32)
print(y)

X, y = pd.DataFrame(X), pd.DataFrame(y)
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y)

api = TabularClassificationTask(seed=42)

api.search(X_train=X_train, y_train=y_train, X_test=X_test, y_test=y_test, optimize_metric='accuracy',
           total_walltime_limit=300, func_eval_time_limit_secs=10)

# Check the statistics (, which has been added in this PR)
print(api.sprint_statistics())
# Check the incumbent (, which has been modified in this PR)
api.get_incumbent_results(include_traditional=True)
```

2021-11-19 16:35 UTC, ravinkohli commented on autoPyTorch/api/results_manager.py
> +        metric: autoPyTorchMetric,
can we have this metric argument as`Optional` ? I think the default behaviour of this function should be to return the incumbent result according to the `self._metric`.

2021-11-19 16:38 UTC, ravinkohli commented on autoPyTorch/api/results_manager.py
> +                A metric that is used to fit AutoPytorch.
```suggestion
                A metric that is evaluated when searching with AutoPytorch.
```

2021-11-19 16:39 UTC, ravinkohli commented on autoPyTorch/api/results_manager.py
> +                A metric that is used to fit AutoPytorch.
I want to avoid using fit as we don't have a `fit` function.

2021-11-19 16:40 UTC, ravinkohli commented on autoPyTorch/api/results_manager.py
> +                A metric that is used to fit AutoPytorch.
same here

2021-11-19 16:49 UTC, ravinkohli requested changes
Overall I think the PR can be merged with a few changes. I have suggested minor changes to the docstring. Also as we are only testing `get_incumbent_results` with the accuracy we should also test for a different metric for example 'logloss' for classification where greater is not better. Could you add it in [`test_get_incumbent_results`](https://github.com/automl/Auto-PyTorch/blob/a1512d56d4db89133e895e85765e3b72afbfe157/test/test_api/test_api.py#L580)?

2021-11-19 22:43 UTC, nabenabe0928 commented
> Overall I think the PR can be merged with a few changes. I have suggested minor changes to the docstring. Also as we are only testing `get_incumbent_results` with the accuracy we should also test for a different metric for example 'logloss' for classification where greater is not better. Could you add it in [`test_get_incumbent_results`](https://github.com/automl/Auto-PyTorch/blob/a1512d56d4db89133e895e85765e3b72afbfe157/test/test_api/test_api.py#L580)?

I addressed it:)

2021-11-20 11:26 UTC, ravinkohli commented on test/test_api/test_results_manager.py
> +        try:
you can use pytest.raises(RuntimeError) instead of try and except.

2021-11-20 11:51 UTC, ravinkohli commented on test/test_api/test_results_manager.py
> +    except RuntimeError:
same here

2021-11-20 11:53 UTC, ravinkohli commented on test/test_api/test_results_manager.py
> +    assert abs(best_score - cost2metric(best_cost, metric)) < 1e-5
do you think we can use [`np.isclose`](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html`)

2021-11-20 11:56 UTC, ravinkohli reviewed
I have suggested some minor changes in the tests. After they are resolved, I think this PR can be merged.

2021-11-21 18:24 UTC, merged